language: java
sudo: required
jdk: oraclejdk8

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jobs:
  include:
  - stage: Tests Unitarios
    script: ./gradlew testUnitarios
  - stage: Test de Integracion
    script: ./gradlew testIntegracion
  - stage: Test End to End
    script: ./gradlew testEndToEnd
  - stage: Mantenibilidad-> Verificar correcta dependencia entre capas
    script: ./gradlew testArquitectura
  - stage: Mantenibilidad -> Verificar que la cobertura de pruebas unitarias sea del 60%
    script: ./gradlew jacocoTestCoverageVerification
  - stage: Seguridad -> Verificar no vulnerabilidades en dependencias del proyecto
    script: npm install -g snyk && snyk test